Modules/Admin/Http/routes.php
<?php

Route::get('/', function () {
	return redirect(route('admin.dashboard.index'));
});

Route::group(['middleware' => [ 'web', 'auth','roles' ], 'as' => 'admin.',
              'prefix' => 'admin', 'namespace' => 'Modules\Admin\Http\Controllers'], function()
{
	// -- Dashboard
	Route::resource('/dashboard', 'DashboardController');

	// -- Capital
	Route::resource('/capital', 'CapitalController');

	// -- Message
	Route::resource('/message', 'MessageController');

    // -- Demonstratives
    Route::resource('/demonstratives', 'DemonstrativeController');

    // -- Finances
    Route::resource('/finances', 'FinanceController');
    // -- Recipes
    Route::resource('/recipes', 'RecipeController');
    // -- Recipes
    Route::resource('/expenses', 'ExpenseController');
    // -- Taxations
    Route::resource('/taxations', 'TaxationController');

	// -- Users
	Route::resource('/users', 'UserController');
	Route::get('/users/{user_id}/login', 'UserController@login')->name('users.login');

	// -- Files
	Route::resource('/files', 'FileController');
	Route::get('/files/{file}/process', 'FileController@process')->name('files.process');

    // -- File Categories
    Route::resource('/file-categories', 'FileCategoryController');

	// -- Settings
	Route::resource('/settings', 'SettingController');

    // -- contributions
    Route::resource('/contributions', 'ContributionController');

     // -- withdrawals
    Route::resource('/withdrawals', 'WithdrawalController');

    // -- Transaction Approve
    Route::resource('/transaction-approve', 'TransactionApproveController');

});


// -- PUBLIC
Route::group(['middleware' => [ 'web'], 'as' => 'admin.','namespace' => 'Modules\Admin\Http\Controllers'], function()
{
    // -- UserAccount
    Route::resource('/accounts', 'UserAccountController');
    Route::get('/accounts/create/{user_shared?}', 'UserAccountController@create')->name('user.indicate_link');

    // -- Notification
    Route::post('/notify', function()
    {
        return Modules\Core\Helpers\RequestHelper::doApiRequest(function(){
            Auth::user()->unreadNotifications->markAsRead();
        });
    })->name('notifiable.mark_as_read');

});



Modules/Admin/Http/Controllers/FinanceController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Routing\Controller;
use Illuminate\Http\Request;
use Modules\Admin\DataTables\RecipesDataTable;
use Modules\Admin\DataTables\TaxationsDataTable;
use Modules\Admin\DataTables\ExpensesDataTable;
use Modules\Core\Entities\Expense;
use Modules\Core\Entities\Recipe;
use Modules\Core\Entities\Taxation;

class FinanceController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @param ExpensesDataTable $expensesDataTable
     * @param RecipesDataTable $recipesDataTable
     * @return \Illuminate\Http\JsonResponse|\Illuminate\View\View
     * @throws \Throwable
     */
    public function index(Request $request, RecipesDataTable $recipesDataTable, ExpensesDataTable $expensesDataTable, TaxationsDataTable $taxationsDataTable)
    {

        $is_expenses = $expensesDataTable->request()->input('datatable_id') == Expense::class;
        $is_recipes = $recipesDataTable->request()->input('datatable_id') == Recipe::class;
        $is_taxations = $taxationsDataTable->request()->input('datatable_id') == Taxation::class;

        if ($expensesDataTable->request()->ajax() && $expensesDataTable->request()->wantsJson() && $is_expenses) {
            return app()->call([$expensesDataTable, 'ajax']);
        }

        if ($recipesDataTable->request()->ajax() && $recipesDataTable->request()->wantsJson() && $is_recipes) {
            return app()->call([$recipesDataTable, 'ajax']);
        }

        if ($taxationsDataTable->request()->ajax() && $taxationsDataTable->request()->wantsJson() && $is_taxations) {
            return app()->call([$taxationsDataTable, 'ajax']);
        }

        $expensesDataTable = $expensesDataTable->getHtmlBuilder();
        $recipesDataTable = $recipesDataTable->getHtmlBuilder();
        $taxationsDataTable = $taxationsDataTable ->getHtmlBuilder();

        $recipesDataTable->scripts();

        return view('admin::pages.finance.index',
            compact('expensesDataTable', 'recipesDataTable','taxationsDataTable'));


    }
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
    	    $dd = 1;//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		//
	}
}

Modules/Admin/Resources/views/pages/finance/_expense_elements/_create.blade.php
{!! Form::open([ 'route' => [ 'admin.expenses.store' ],'files' => true, 'expenses' => 'create']) !!}
<div class="modal fade" id="expenseModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg " role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">ENTRE COM OS DADOS PARA UMA NOVA DISPENSA</h4>
            </div>
            <div class="modal-body">

                <div class="body  form-horizontal">

                    <div class="row">&nbsp;</div>

                    <div class="row">&nbsp;</div>
                    <div class="form-group">
                        <label for="company_name" class="col-sm-3 control-label">VALOR: </label>
                        <div class="col-sm-8">
                            <div class="form-line">
                                {!! Form::text('value', null, [ 'class' => 'form-control mask-money-real' ]) !!}
                            </div>
                        </div>
                    </div>

                    <div class="row">&nbsp;</div>
                    <div class="form-group">
                        <label for="company_name" class="col-sm-3 control-label">DATA: </label>
                        <div class="col-sm-8">
                            <div class="form-line">
                                {!! Form::date('date', null, [ 'class' => 'form-control' ]) !!}
                            </div>
                        </div>
                    </div>


                    <div class="row">&nbsp;</div>
                    <div class="form-group">
                        <label for="company_name" class="col-sm-3 control-label">DESTINARÁRIO:  </label>
                        <div class="col-sm-8">
                            <div class="form-line">
                                {!! Form::text('addressee', null, [ 'class' => 'form-control' ]) !!}
                            </div>
                        </div>
                    </div>

                    <div class="row">&nbsp;</div>
                    <div class="form-group">
                        <label for="company_name" class="col-sm-3 control-label">NATUREZA: </label>
                        <div class="col-sm-8">
                            <div class="form-line">
                                {!! Form::text('kind', null, [ 'class' => 'form-control' ]) !!}
                            </div>
                        </div>
                    </div>


                    <div class="row">&nbsp;</div>
                    <div class="row">&nbsp;</div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CANCELAR</button>
                <button type="submit" class="btn btn-success btn-lg waves-effect">ENVIAR</button>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!}


@push('scripts')
    <script type="application/javascript">

        $(document).ready(function () {



            $('.mask-money-real').inputmask( 'currency',{"autoUnmask": true,
                radixPoint:",",
                removeMaskOnSubmit: true,
                groupSeparator: ".",
                allowMinus: false,
                prefix: 'R$ ',
                digits: 2,
                digitsOptional: false,
                rightAlign: false,
                unmaskAsNumber: true,
                min:0,
            });

        });

    </script>
@endpush

Modules/Admin/Resources/views/pages/finance/_expense_elements/_edit.blade.php
{!! Form::open(['route' => ['admin.expenses.update', null],'files' => true, 'expenses' => 'edit']) !!}
{!! Form::hidden('_method', 'put') !!}
<div class="modal fade" id="editModalExpense" tabindex="-1" role="dialog">
    <div class="modal-dialog  modal-lg " role="document" id="expenseApp">
        <div v-if="_.isEmpty(response_message)" class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="uploadModalLabelExpense">Solicitação de aporte</h4>
            </div>
            <div class="modal-body align-center" >
                <div class="row">&nbsp;</div>
                <div class="row">&nbsp;</div>
                <div v-if="isLoader" class="body">
                    <div class="preloader">
                        <div class="spinner-layer pl-teal">
                            <div class="circle-clipper left">
                                <div class="circle"></div>
                            </div>
                            <div class="circle-clipper right">
                                <div class="circle"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div v-else class="body form-horizontal">


                    <div class="form-group">
                        <label for="company_name" class="col-sm-3 control-label">VALOR: </label>
                        <div class="col-sm-8">
                            <div class="form-line">
                                {!! Form::text('value', null,
                                    [
                                        'class' => 'form-control mask-money-real',
                                        'v-model' => 'expense.value'
                                    ])
                                !!}
                            </div>
                        </div>
                    </div>
                    <div class="row">&nbsp;</div>

                    <div class="row">&nbsp;</div>
                    <div class="form-group">
                        <label for="company_name" class="col-sm-3 control-label">DATA: </label>
                        <div class="col-sm-8">
                            <div class="form-line">
                                {!! Form::date('date', null, [ 'class' => 'form-control','v-model' => 'expense.date' ]) !!}
                            </div>
                        </div>
                    </div>


                    <div class="row">&nbsp;</div>
                    <div class="form-group">
                        <label for="company_name" class="col-sm-3 control-label">DESTINATÁRIO:  </label>
                        <div class="col-sm-8">
                            <div class="form-line">
                                {!! Form::text('addressee', null, [ 'class' => 'form-control','v-model' => 'expense.addressee'  ]) !!}
                            </div>
                        </div>
                    </div>

                    <div class="row">&nbsp;</div>
                    <div class="form-group">
                        <label for="company_name" class="col-sm-3 control-label">NATUREZA: </label>
                        <div class="col-sm-8">
                            <div class="form-line">
                                {!! Form::text('kind', null, [ 'class' => 'form-control','v-model' => 'expense.kind' ]) !!}
                            </div>
                        </div>
                    </div>


                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CANCELAR</button>
                <button type="button" @click="formSubmit()" class="btn btn-success waves-effect">SALVAR</button>
            </div>
        </div>
        <div v-else class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="uploadModalLabelExpense">Solicitação de aporte</h4>
            </div>
            <div class="modal-body align-center" >
                <div class="row">&nbsp;</div>
                <div class="row">&nbsp;</div>
                <div class="body">
                    <div v-if="response_message.status == 'success'">
                        <h5>TUDO CERTO... OS DADOS FORAM SALVOS!</h5>
                        <div class="alert bg-green">
                            @{{response_message.message}}
                        </div>
                    </div>
                    <div v-else >
                        <h5>OPS... Algo de deu errado</h5>
                        <div class="alert bg-danger">
                            @{{response_message.message}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect" @click="setPatterns()" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!}


@push('scripts')

    <script type="application/javascript">

        var expenseApp = new Vue({
            el: '#expenseApp',
            data: {
                isLoader: true,
                response_message: {},
                expense: {},
            },
            methods: {

                /*
                  Set default of this application after actions
                */
                setPatterns(){

                    this.response_message = {};
                    this.expense = {};
                    this.isLoader = true;

                },

                /*
                 Ajax with expense data
               */
                getExpenses(id){

                    this.setPatterns();

                    var that = this;

                    $.ajax({
                        url: "{{ route('api.expenses.show',null) }}" + "/" +id,
                        method: 'GET',
                        beforeSend: function () {
                            Vue.set(that,'isLoader', true);
                        }
                    })
                    /*
                       Do something when it completes successfully
                    */
                        .done(function(response)
                        {
                            that.expense = response.data;
                        })
                        /*
                           Do something when it fails
                        */
                        .fail(function(response)
                        {
                            console.log(response.responseJSON);
                        })
                        /*
                           Do something ever
                        */
                        .always(function(response)
                            {
                                Vue.set(that,'isLoader', false);
                            }
                        );

                },

                formSubmit: function () {


                    var that = this;
                    var expense = Object.assign({}, this.expense);
                    this.setPatterns();

                    $.ajax({

                        url: "{{ route('api.expenses.update',null) }}" + "/" + expense.id,
                        method: 'PUT',
                        dataType: 'json',
                        data: expense,

                        beforeSend: function () {
                            // Code before send here
                        }
                    })
                    /*
                      Do something when it completes successfully
                   */
                        .done(function(response)
                        {
                            if(typeof response == 'string')
                                that.response_message = JSON.parse(response);
                            else
                                that.response_message = response;

                            LaravelDataTables.expenses.ajax.reload()
                        })
                        /*
                           Do something when it fails
                        */
                        .fail(function(response)
                        {
                            if(typeof response.responseJSON == 'string')
                                that.response_message = JSON.parse(response.responseJSON);
                            else
                                that.response_message = response.responseJSON;
                        })
                        /*
                           Do something ever
                        */
                        .always(function(response)
                            {
                                Vue.set(that,'isLoader', false);
                            }
                        );

                }
            },
            updated: function () {

            }
        });

    </script>
@endpush