Modules/Admin/Http/routes.php
<?php

Route::get('/', function () {
	return redirect(route('admin.dashboard.index'));
});

Route::group(['middleware' => [ 'web', 'auth','roles' ], 'as' => 'admin.',
              'prefix' => 'admin', 'namespace' => 'Modules\Admin\Http\Controllers'], function()
{
	// -- Dashboard
	Route::resource('/dashboard', 'DashboardController');

	// -- Capital
	Route::resource('/capital', 'CapitalController');

	// -- Message
	Route::resource('/message', 'MessageController');

    // -- Demonstratives
    Route::resource('/demonstratives', 'DemonstrativeController');

    // -- Finances
    Route::resource('/finances', 'FinanceController');
    // -- Recipes
    Route::resource('/recipes', 'RecipeController');
    // -- Recipes
    Route::resource('/expenses', 'ExpenseController');
    // -- Taxations
    Route::resource('/taxations', 'TaxationController');

	// -- Users
	Route::resource('/users', 'UserController');
	Route::get('/users/{user_id}/login', 'UserController@login')->name('users.login');

	// -- Files
	Route::resource('/files', 'FileController');
	Route::get('/files/{file}/process', 'FileController@process')->name('files.process');

    // -- File Categories
    Route::resource('/file-categories', 'FileCategoryController');

	// -- Settings
	Route::resource('/settings', 'SettingController');

    // -- contributions
    Route::resource('/contributions', 'ContributionController');

     // -- withdrawals
    Route::resource('/withdrawals', 'WithdrawalController');

    // -- Transaction Approve
    Route::resource('/transaction-approve', 'TransactionApproveController');

});


// -- PUBLIC
Route::group(['middleware' => [ 'web'], 'as' => 'admin.','namespace' => 'Modules\Admin\Http\Controllers'], function()
{
    // -- UserAccount
    Route::resource('/accounts', 'UserAccountController');
    Route::get('/accounts/create/{user_shared?}', 'UserAccountController@create')->name('user.indicate_link');

    // -- Notification
    Route::post('/notify', function()
    {
        return Modules\Core\Helpers\RequestHelper::doApiRequest(function(){
            Auth::user()->unreadNotifications->markAsRead();
        });
    })->name('notifiable.mark_as_read');

});



Modules/Admin/Resources/views/layout/blankpage.blade.php
@include('admin::layout.header')

<body background="{{  Module::asset('admin:images/new-account-business.jpg')  }}">

    {{--<!-- Top Bar -->--}}
    {{--<nav class="navbar">--}}
        {{--<div class="container-fluid">--}}

            {{--<a class="page-title" href="{{ route('admin.dashboard.index') }}">--}}
                {{-- <img src="{{ Module::asset('admin:images/logo1.png') }}" height="60px;" />--}}
                {{--<span style="font-size: 36px; padding-top: 10px;">--}}
                {{--{{ ConfigHelper::get('site_title') }}--}}
                {{--<small>| @yield('page_title')</small>--}}
                {{--</span>--}}
            {{--</a>--}}

            {{--<div class="navbar-header">--}}
                {{--<a href="javascript:void(0);" class="bars"></a>--}}
                {{--<a class="navbar-brand" href="javascript:void(0);">ADMIN - Portal Invista em Consórcio</a>--}}
            {{--</div>--}}

            {{--<div class="collapse navbar-collapse" id="navbar-collapse">--}}
                {{--<ul class="nav navbar-nav navbar-right">--}}

                {{--</ul>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</nav>--}}
    {{--<!-- #Top Bar -->--}}



    <section class="content">
        <div class="container-fluid">
            {{--<div class="block-header">--}}
            <div>
                <div id="app">

                    @yield('content')
                </div>

            </div>
        </div>
    </section>

    @include('admin::layout.footer')

</body>

Modules/Admin/Resources/views/layout/colors.blade.php
<style type="text/css">
    .theme-red .navbar {
        background-color: #2687ea !important;
        padding-top: 10px;
    }
</style>

Modules/Admin/Resources/views/layout/footer.blade.php
<!-- Jquery Core Js -->
<script src="{{ Module::asset('core:plugins/jquery/jquery.min.js') }}"></script>

<!-- Bootstrap Core Js -->
<script src="{{ Module::asset('core:plugins/bootstrap/js/bootstrap.js') }}"></script>

<!-- Bootstrap select -->
<script src="{{ Module::asset('core:plugins/bootstrap-select/js/bootstrap-select.min.js') }}"></script>

<!-- Bootstrap select - Ajax extension -->
<script src="{{ Module::asset('core:plugins/bootstrap-select-ajax/js/ajax-bootstrap-select.min.js') }}"></script>

<!-- Slimscroll Plugin Js -->
<script src="{{ Module::asset('core:plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

<!-- Waves Effect Plugin Js -->
<script src="{{ Module::asset('core:plugins/node-waves/waves.js') }}"></script>

<!-- Light Gallery Plugin Js -->
<script src="{{ Module::asset('core:plugins/light-gallery/js/lightgallery-all.js') }}"></script>

<!-- Custom Js -->
<script src="{{ Module::asset('core:js/admin.js') }}"></script>

<!-- Demo Js -->
<script src="{{ Module::asset('core:js/demo.js') }}"></script>

<!-- Sweet Alerts -->
<script src="{{ Module::asset('core:plugins/sweetalert/sweetalert.min.js') }}"></script>

<!-- Popovers -->
<script src="{{ Module::asset('core:js/pages/ui/tooltips-popovers.js') }}"></script>

<!-- JQUERY: Plugin MASK -->
<script src="{{ Module::asset('core:plugins/jquery.mask/jquery.mask.min.js') }}" type="text/javascript" ></script>

<!-- Input Mask Plugin Js -->
<script src="{{ Module::asset('core:plugins/jquery-inputmask/jquery.inputmask.bundle.js') }}"></script>

<!-- Moment Plugin Js -->
<script src="{{ Module::asset('core:plugins/momentjs/moment.js') }}" type="text/javascript" ></script>

<!-- Bootstrap Material Datetime Picker Plugin Js -->
<script src="{{ Module::asset('core:plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}"></script>

<!-- Count To -->
<script src="{{ Module::asset('core:plugins/jquery-countto/jquery.countTo.js') }}"></script>

<!-- Lodash JS -->
<script src="{{ Module::asset('core:plugins/lodash/lodash.min.js') }}"></script>

<!-- Core -->
<script src="{{ Module::asset('core:app/general.js') }}"></script>

<!-- Admin -->
<script src="{{ Module::asset('admin:app/general.js') }}"></script>


@if(App::environment('local') || App::environment('development'))
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js"></script>
@elseif(App::environment('production'))
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.min.js"></script>
@endif

{{--<script src="{{ Module::asset('core:app/vue/app.js') }}"></script>--}}


@stack('scripts')

</body>

</html>

Modules/Admin/Resources/views/layout/header.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <title>{{ ConfigHelper::get('site_title') }} - @yield('page_title')</title>
  <link rel="icon" href="{{ Module::asset('admin:images/logo.ico') }}">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

  <!-- Bootstrap Core Css -->
  <link href="{{ Module::asset('core:plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

  <!-- Waves Effect Css -->
  <link href="{{ Module::asset('core:plugins/node-waves/waves.css') }}" rel="stylesheet">

  <!-- Animation Css -->
  <link href="{{ Module::asset('core:plugins/animate-css/animate.css') }}" rel="stylesheet">

  <!-- Sweetalert Css -->
  <link href="{{ Module::asset('core:plugins/sweetalert/sweetalert.css') }}" rel="stylesheet">

  <!-- Light Gallery Plugin Css -->
  <link href="{{ Module::asset('core:plugins/light-gallery/css/lightgallery.css') }}" rel="stylesheet">

  <!-- Multi Select Css -->
  <link href="{{ Module::asset('core:plugins/multi-select/css/multi-select.css') }}" rel="stylesheet">

  <!-- Bootstrap Spinner Css -->
{{--  <link href="{{ Module::asset('core:plugins/query-spinner/css/bootstrap-spinner.css') }}" rel="stylesheet">--}}

  <!-- Bootstrap Tagsinput Css -->
  <link href="{{ Module::asset('core:plugins/bootstrap-tagsinput/bootstrap-tagsinput.css') }}" rel="stylesheet">

  <!-- Bootstrap select -->
  <link href="{{ Module::asset('core:plugins/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet">

  <!-- Bootstrap select - Ajax extension -->
  <link href="{{ Module::asset('core:plugins/bootstrap-select-ajax/css/ajax-bootstrap-select.min.css') }}" rel="stylesheet">

  <!-- Bootstrap Material Datetime Picker Css -->
  <link href="{{ Module::asset('core:plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}" rel="stylesheet" />

  <!-- noUISlider Css -->
  <link href="{{ Module::asset('core:plugins/nouislider/nouislider.min.css') }}" rel="stylesheet">

  <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
  <link href="{{ Module::asset('core:css/themes/all-themes.css') }}" rel="stylesheet">

  <!-- Custom Css -->
  <link href="{{ Module::asset('core:css/style.css') }}" rel="stylesheet">

  <!-- General Css -->
  <link href="{{ Module::asset('core:app/general.css') }}" rel="stylesheet">

  <!-- General Css -->
  <link href="{{ Module::asset('admin:app/general.css') }}" rel="stylesheet">


  @stack('css')

  {{-- CUSTOM COLORS --}}
  @include('admin::layout.colors')
  <style>
    .sidebar .menu .list .header{
        color: #c3bec9;
        padding: 18px 16px !important;
        background: {!!  ConfigHelper::get('secondary_color') !!} !important;
    }

    .theme-blue-grey .sidebar .menu .list li.active > :first-child i, .theme-blue-grey .sidebar .menu .list li.active > :first-child span{
      color: {!!  ConfigHelper::get('secondary_color') !!} !important;
      font-weight: bold !important;
    }
  </style>

</head>

<body class="theme-blue-grey {{ isset($extra_class) ? $extra_class : '' }}">

Modules/Admin/Resources/views/layout/master.blade.php
@include('admin::layout.header')
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Processando...</p>
    </div>
</div>
<!-- #END# Page Loader -->

<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->

<!-- Search Bar -->
{{--@include('admin::layout.searchbar')--}}
<!-- #END# Search Bar -->

<!-- Top Bar -->
<nav class="navbar"
     style="background-color: {!!  ConfigHelper::get('primary_color') !!}">
    <div class="container-fluid">

        {{--<a class="page-title" href="{{ route('admin.dashboard.index') }}">--}}
             {{--<img src="{{ Module::asset('admin:images/logo.png') }}" height="60px;" />--}}
        {{--</a>--}}

        <div class="navbar-header" style="padding: 0" >
            <a href="javascript:void(0);" class="bars"></a>
            <img class="visible-lg" src="{{ Module::asset('admin:images/logo.png') }}" height="74px;" width="108px" />
            <img class="visible-xs visible-sm visible-md" src="{{ Module::asset('admin:images/logo.png') }}"
                 height="74px;"
                 width="108px"
                 style="margin-left: 37px"
            />
{{--            <img src="{{ Module::asset('admin:images/logo.png') }}" height="60px;" />--}}
            {{--<a class="navbar-brand" href="javascript:void(0);"><strong>ADMIN || </strong><span style="color: #b38b4b">INVESTE Consórcio</span></a>--}}
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

                <!-- Call Search -->
            {{--<li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>--}}
            <!-- #END# Call Search -->

            <!-- USER - SHARE -->
            <li class="dropdown m-l--20" style=" margin-right: 15px; ">
                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                    <i class="material-icons">share</i>
                </a>
                <ul class="dropdown-menu">
                    <li class="header col-blue-grey">Link de compartilhamento</li>
                    <li class="footer">
                        <a href="javascript:void(0);" class="col-light-blue"
                           onclick="javascript:  window.prompt('Aperte ok para copiar o link abaixo:', '{{route('admin.user.indicate_link',Auth::getUser()->code_shared)}}');">

                            Https://.../{{Auth::getUser()->code_shared}}
                            <i class="material-icons" style="float: right">content_copy</i>
                        </a>
                    </li>
                </ul>

            </li>


            <!-- USER - INFO -->
            <li class="dropdown">
                <a href="javascript:void(0);" class="dropdown-toggle  waves-effect" data-toggle="dropdown" role="button" style=" padding: 0; ">
                    <div class="image-area" style=" display: flex; ">
                        <img src="https://gurayyarar.github.io/AdminBSBMaterialDesign/images/user-lg.jpg" id="display_profile_image"
                             alt="AdminBSB - Profile Image" style="/* width: 79px; */height: 39px;padding: 0;margin: 0;border-radius: 48px;" />

                        <p style="align-self: center; padding: 0 9px; margin: 0;">{{  Auth::getUser()->account->full_name }}</p>
                    </div>
                </a>
                @include('admin::layout.components._user_info')
            </li>



            <!-- Notifications -->
            <li class="dropdown">
                <a href="{{ route('admin.notifiable.mark_as_read') }}" id="notifiable" class="dropdown-toggle  waves-effect" data-toggle="dropdown" role="button">
                    <i class="material-icons">notifications</i>
                    <span class="label-count">{{ \Auth::getUser()->unreadNotifications()->count()  }}</span>
                </a>
                @include('admin::layout.components._notifications')
            </li>
            <!-- #END# Notifications -->

            <!-- Messages -->
            <li class="dropdown">
                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                    <i class="material-icons">mail</i>
                    <span class="label-count">3</span>
                </a>
                @include('admin::layout.components._messages')
            </li>
            <!-- #END# Messages -->


            {{--<!-- Tasks -->--}}
            {{--<li class="dropdown">--}}
                {{--<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">--}}
                    {{--<i class="material-icons">flag</i>--}}
                    {{--<span class="label-count">9</span>--}}
                {{--</a>--}}
                {{--@include('admin::layout.components._tasks')--}}
            {{--</li>--}}
            {{--<!-- #END# Tasks -->--}}



                {{--<li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true">--}}
                {{--<i class="material-icons">more_vert</i></a>--}}
                {{--</li>--}}

            </ul>
        </div>
    </div>
</nav>
<!-- #Top Bar -->

<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">

        <!-- User Info -->
        {{--<div class="user-info">--}}
            {{--<div class="gas-station"></div>--}}
            {{--<div style="width: 48px; height: 48px;"></div>--}}
            {{--<div class="image">--}}
            {{--<img src="{{ Module::asset('customer:images/user.png') }}" width="48" height="48" alt="User" />--}}
            {{--</div>--}}
            {{--<div class="info-container">--}}
                {{--<div class="name col-white" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">--}}
                    {{--{{ Auth::getUser()->account->full_name }} ({{ Auth::getUser()->roles()->first()->name }})--}}
                {{--</div>--}}
                {{--<div class="email" style="color: rgba(255, 255, 255, .5)">{{ Auth::getUser()->email }}</div>--}}
                {{--<div class="btn-group user-helper-dropdown">--}}
                    {{--<i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>--}}
                    {{--<ul class="dropdown-menu pull-right">--}}
                        {{--<li>--}}
                            {{--<a href="{{ route('admin.users.edit', \Auth::getUser()->id) }}">--}}
                                {{--<i class="material-icons">person</i>Perfil--}}
                            {{--</a>--}}
                        {{--</li>--}}
                        {{--<li role="seperator" class="divider"></li>--}}
                        {{--<li><a href="{{ route('logout') }}"><i class="material-icons">input</i>Logout</a></li>--}}
                    {{--</ul>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
        <!-- #User Info -->

        <!-- Menu -->
    @include('admin::layout.menu')
    <!-- #Menu -->

        <!-- Footer -->
        <div class="legal">
            <div class="version">
                © 2013 - {{ date('Y') }} {{ ConfigHelper::get('site_title') }} <br>
                <small><b>Versão </b> 3.0.0</small>
            </div>
        </div>
        <!-- #Footer -->

    </aside>
    <!-- #END# Left Sidebar -->

    <!-- Right Sidebar -->
{{--@include('admin::layout.rightbar')--}}
<!-- #END# Right Sidebar -->

</section>

<section class="content">
    <div class="container-fluid">
        {{--<div class="block-header">--}}
        <div>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif

            <div id="app">
                {!! Breadcrumbs::render() !!}

                @yield('content')
            </div>

        </div>
    </div>
</section>

@include('admin::layout.footer')

Modules/Admin/Resources/views/layout/menu.blade.php
<div class="menu">
    <ul class="list">
        <li class="header">NAVEGAÇÃO PRINCIPAL</li>
        <li class="active" style="display: none;"></li>


        <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\DashboardController::class) }}">
            <a href="{{ route('admin.dashboard.index') }}">
                <i class="material-icons">home</i>
                <span>HOME</span>
            </a>
        </li>

        @if( Permission::canDo( Permission::ACTION_LIST, Permission::CAPITAL) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\CapitalController::class) }}">
                <a href="{{ route('admin.capital.index') }}">
                    <i class="material-icons">account_balance</i>
                    <span>Capital (Extrato)</span>
                </a>
            </li>
        @endif

        @if( Permission::canDo( Permission::ACTION_LIST, Permission::DEMONSTRATIVE) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\DemonstrativeController::class) }}">
                <a href="{{ route('admin.demonstratives.index') }}">
                    <i class="material-icons">insert_chart</i>
                    <span>Resultados</span>
                </a>
            </li>
        @endif



        @if( Permission::canDo( Permission::ACTION_LIST, Permission::TRANSACTION) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\TransactionApproveController::class) }}">
                <a href="{{ route('admin.transaction-approve.index') }}">
                    <i class="material-icons">done</i>
                    <span>Aprovar Transações</span>
                </a>
            </li>
        @endif

        @if( Permission::canDo( Permission::ACTION_LIST, Permission::CONTRIBUTION) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\ContributionController::class) }}">
                <a href="{{ route('admin.contributions.index') }}">
                    <i class="material-icons">add</i>
                    <span>Aportes (Aumento de capital)</span>
                </a>
            </li>
        @endif

        @if( Permission::canDo( Permission::ACTION_LIST, Permission::CONTRIBUTION) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\WithdrawalController::class) }}">
                <a href="{{ route('admin.withdrawals.index') }}">
                    <i class="material-icons">remove</i>
                    <span>Resgates</span>
                </a>
            </li>
        @endif

        @if( Permission::canDo( Permission::ACTION_LIST, Permission::FINANCE) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\FinanceController::class) }}">
                <a href="{{ route('admin.finances.index') }}">
                    <i class="material-icons">attach_money</i>
                    <span>Financeiro</span>
                </a>
            </li>
        @endif

        @if( Permission::canDo( Permission::ACTION_LIST, Permission::MESSAGE) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\MessageController::class) }}">
                <a href="{{ route('admin.message.index') }}">
                    <i class="material-icons">message</i>
                    <span>Mensagens</span>
                </a>
            </li>
        @endif

        @if( Permission::canDo( Permission::ACTION_LIST, Permission::USER) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\UserController::class) }}">
                <a href="{{ route('admin.users.index') }}">
                    <i class="material-icons">accessibility</i>
                    <span>Usuários</span>
                </a>
            </li>
        @endif

        {{--@if( Permission::canDo( Permission::ACTION_LIST, Permission::FILE) )--}}
            {{--<li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\FileController::class) }}">--}}
                {{--<a href="{{ route('admin.files.index') }}">--}}
                    {{--<i class="material-icons">attach_file</i>--}}
                    {{--<span>Arquivos</span>--}}
                {{--</a>--}}
            {{--</li>--}}
        {{--@endif--}}

        @if( Permission::canDo( Permission::ACTION_LIST, Permission::SETTING) )
            <li class="{{ AppHelper::menuActive(\Modules\Admin\Http\Controllers\SettingController::class) }}">
                <a href="{{ route('admin.settings.index') }}">
                    <i class="material-icons">settings</i>
                    <span>Configurações</span>
                </a>
            </li>
        @endif

        <li>
            <a href="javascript:void(0);" class="menu-toggle waves-effect waves-block">
                <i class="material-icons">picture_as_pdf</i>
                <span>Contratos</span>
            </a>
            <ul class="ml-menu" style="display: none;">
                <li>
                    <a href="{!! \Module::asset('admin:pdfs/contrato.pdf') !!}" target="_blank" class=" waves-effect waves-block">Contrato 1</a>
                </li>
                <li>
                    <a href="{!! \Module::asset('admin:pdfs/contrato.pdf') !!}" target="_blank" class=" waves-effect waves-block">Contrato 2</a>
                </li>
                <li>
                    <a href="{!! \Module::asset('admin:pdfs/contrato.pdf') !!}" target="_blank" class=" waves-effect waves-block">Contrato 3</a>
                </li>
            </ul>
        </li>
    </ul>
</div>

Modules/Admin/Resources/views/layout/searchbar.blade.php
<div class="search-bar">
<div class="search-icon">
<i class="material-icons">search</i>
</div>
<input type="text" placeholder="START TYPING...">
<div class="close-search">
<i class="material-icons">close</i>
</div>
</div>